apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  labels:
    app: nginx
  annotations:
    "pod.beta.kubernetes.io/hostname": nginx
    "pod.beta.kubernetes.io/subdomain": web
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
