apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: compositecontrollers.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: compositecontrollers
    singular: compositecontroller
    kind: CompositeController
    shortNames:
    - cc
    - cctl
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: initializercontrollers.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: initializercontrollers
    singular: initializercontroller
    kind: InitializerController
    shortNames:
    - ic
    - ictl
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllerrevisions.metacontroller.k8s.io
spec:
  group: metacontroller.k8s.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: controllerrevisions
    singular: controllerrevision
    kind: ControllerRevision
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metacontroller
  namespace: metacontroller
  labels:
    app: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metacontroller
  template:
    metadata:
      labels:
        app: metacontroller
    spec:
      serviceAccountName: metacontroller
      containers:
      - name: metacontroller
        image: gcr.io/enisoc-kubernetes/metacontroller:0.1
        imagePullPolicy: Always
        command: ["/usr/bin/metacontroller"]
        args:
        - --logtostderr
        - -v=4
        - --discovery-interval=10s
