apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: catsets.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  version: v1
  scope: Namespaced
  names:
    plural: catsets
    singular: catset
    kind: CatSet
    shortNames:
    - cs
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: catset-controller
spec:
  parentResource:
    apiVersion: ctl.enisoc.com/v1
    resource: catsets
  childResources:
    - apiVersion: v1
      resources: ["pods", "persistentvolumeclaims"]
  clientConfig:
    service:
      name: catset-controller
      namespace: metacontroller
    caBundle: ...
  hooks:
    sync:
      path: /sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: catset-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catset-controller
  template:
    metadata:
      labels:
        app: catset-controller
    spec:
      containers:
      - name: controller
        image: gcr.io/enisoc-kubernetes/nodejs-server:latest
        volumeMounts:
        - name: hooks
          mountPath: /node/hooks
      volumes:
      - name: hooks
        configMap:
          name: catset-controller
---
apiVersion: v1
kind: Service
metadata:
  name: catset-controller
  namespace: metacontroller
spec:
  selector:
    app: catset-controller
  ports:
  - port: 80
