# Override image for development mode (skaffold fills in the tag).
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: metacontroller
  namespace: metacontroller
spec:
  serviceName: ""
  template:
    spec:
      containers:
      - name: metacontroller
        image: enisoc/metacontroller
