apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bluegreendeployments.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  version: v1
  scope: Namespaced
  names:
    plural: bluegreendeployments
    singular: bluegreendeployment
    kind: BlueGreenDeployment
    shortNames:
    - bgd
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: LambdaController
metadata:
  name: bluegreendeployment-controller
spec:
  parentResource:
    apiVersion: ctl.enisoc.com/v1
    resource: bluegreendeployments
  childResources:
  - apiVersion: v1
    resources: ["services"]
  - apiVersion: extensions/v1beta1
    resources: ["replicasets"]
  clientConfig:
    service:
      name: router
      namespace: fission
    caBundle: ...
  hooks:
    sync:
      path: /ctl.enisoc.com/bluegreendeployments/sync
