apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bluegreendeployments.ctl.enisoc.com
spec:
  group: ctl.enisoc.com
  version: v1
  scope: Namespaced
  names:
    plural: bluegreendeployments
    singular: bluegreendeployment
    kind: BlueGreenDeployment
    shortNames:
    - bgd
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: bluegreen-controller
spec:
  parentResource:
    apiVersion: ctl.enisoc.com/v1
    resource: bluegreendeployments
  childResources:
  - apiVersion: v1
    resources: ["services"]
  - apiVersion: extensions/v1beta1
    resources: ["replicasets"]
  clientConfig:
    service:
      name: bluegreen-controller
      namespace: metacontroller
    caBundle: ...
  hooks:
    sync:
      path: /sync
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bluegreen-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen-controller
  template:
    metadata:
      labels:
        app: bluegreen-controller
    spec:
      containers:
      - name: controller
        image: gcr.io/enisoc-kubernetes/nodejs-server:latest
        volumeMounts:
        - name: hooks
          mountPath: /node/hooks
      volumes:
      - name: hooks
        configMap:
          name: bluegreen-controller
---
apiVersion: v1
kind: Service
metadata:
  name: bluegreen-controller
  namespace: metacontroller
spec:
  selector:
    app: bluegreen-controller
  ports:
  - port: 80
